### ISSUE TITLE
Containers don't come up after reboot or rclean

### ISSUE THREAD

**Issue by Coxeroni** [TechPerplexed/Gooby#113] opened 2019-11-23 08:45 UTC
For some days I have the issue that after a reboot or running rclean, my containers don't come up again.
I already pin-pointed the issue: the docker-compose file is lacking the first two lines, namely the version and services. Therefore the format is invalid and docker-compose refuses to start anything.
I don't know where this comes from, but I will be happily sharing any info if needed.

**Comment by TechPerplexed** [comment] 2019-11-23 15:53
Hmmm, could you check please if the 00-version.yaml file got copied correctly to the Gooby Docker/components folder? It should have replaced the 00-AAA file that was already there, but somehow it sounds like it didn't do this in your case!

**Comment by TechPerplexed** [comment] 2019-11-23 15:54
Sorry should have been more specific - if it's not there, copy the`/opt/Gooby/scripts/nginx/00-version.yaml` file to `/var/local/Gooby/Docker/components` 😄

**Comment by Coxeroni** [comment] 2019-11-23 15:57
Correct, there is no 00-*.yaml file in my components folder.
Any idea why? I will try to run rclean manually again and check for the output.

**Comment by TechPerplexed** [comment] 2019-11-23 16:01
No, if it's not there you will need to copy it manually - running rclean won't help. As for why it wouldn't work, I'm not sure... maybe you can see what went wrong :)

This is the code that SHOULD have run with the upgrade to the latest version:

```
if [ -e ${CONFIGS}/Docker/components/00-AAA.yaml ]; then
PROXYVERSION=$(cat ${CONFIGVARS}/proxyversion)
sudo rsync -a /opt/Gooby/scripts/${PROXYVERSION}/{00-version.yaml,01-proxy.yaml,99-network.yaml} ${CONFIGS}/Docker/components
sudo rm ${CONFIGS}/Docker/components/00-AAA.yaml
fi
```

Yet, somehow, in your case, that didn't didn't happen. Yet it worked for me in all my tests, as well as with many other people who upgraded... 

Did the 99-network.yaml (empty file but needed for future updates) copy without a hitch or isn't that in the folder either?

**Comment by Coxeroni** [comment] 2019-11-23 23:47
No 99-*.yaml in the components folder either.

**Comment by TechPerplexed** [comment] 2019-11-23 23:53
Thanks... so obviously the copy command above is intermittent. Thanks for confirming! (and no need to copy the file, it's the 00 that is important here)

**Comment by Coxeroni** [comment] 2019-11-24 13:14
So I just copy the 00 yaml file and hope for the best in the future? ;)

**Comment by TechPerplexed** [comment] 2019-11-24 16:55
That should be "master" (without the quotes) - it's only meant for testing purposes because testing another branch was driving me nuts before, haha. It probably won't affect anything if it's left empty, but just to be sure you might consider updating it.

Thanks for the heads up on that as well! This was a fairly large update and obviously it didn't go flawless for everyone... which is always good to know for next time :)

**Comment by Coxeroni** [comment] 2019-11-24 16:59
Setting the master branch in .env solved the update issue, will try rclean later if I find the time.

**Comment by TechPerplexed** [comment] 2019-11-24 17:00
OH I missed one of your points: the proxyversion file is absolutely vital - that should definitely be filled with "nginx" (again without quotes) - which is what caused your files not to copy and would also give you troubles if you installed new containers. I'll be working on a patch the coming days, but please fill that out now...

And obviously setting "master" is important as well... now to figure out why these things wouldn't fill for you (I suspect a permission issue BUT upgrades should always work properly, right?)

**Comment by Coxeroni** [comment] 2019-11-24 17:01
Thanks for the help, will give rclean a roll later.

**Comment by TechPerplexed** [comment] 2019-11-25 19:09
And you thanks for the bug report :) Unfortunately I have not been able to reproduce the issue myself, and so far we have had only one error report. 

However, I have edited the check for an empty file (instead of whether it exists or not). Would you mind terribly to test the upgrade once more? There will be a little involved to pretend the upgrade didn't happen:

- You'd need to remove the "version" and "proxyversion" files in the Docker/.config folder
- You need create a bogus 00-AAA.yaml in Docker/components
- Also remove the 99 file in Components if it's there.

Then run rclean again and see if the 00-version and 99-network files copy correctly this time and the proxyversion file is filled with "nginx". I just tested the above on mine and everything works... but then again it worked before so that doesn't prove anything.

If you don't wish to test, that's okay too... no hard feelings (and let's hope very much that you remain the only one with the issue, haha).

**Comment by Coxeroni** [comment] 2019-11-25 19:40
Ok I did as instructed and the following happened:
- the bogus 00-AAA.yaml was incorporated into the compose file and fooked up the whole process. 
- proxyversion and version were recreated correctly
- 00-version and 99-network were not copied. The compose file came up fine nevertheless, maybe because I renamed 00-version to 00-version.yaml.bak and it might still got processed and it contained the right data.

**Comment by TechPerplexed** [comment] 2019-11-25 20:18
Thanks! So, if I understand you correctly:

- This time, the file `proxyversion` was created with the content "nginx" (this didn't happen before) and
- The file `version` was created as well with the content 2.2.1 (as before)

However,

- The `00-AAA.yaml` file was not deleted (unlike before) and
- The `00-version.yaml` and `99-network.yaml` were not copied (as before)

That just doesn't make sense! However, as long as you remain the only one with the issue, I am not going to spend hours and hours of troubleshooting - I'm going to assume it's something odd on your side 🤣 

So, for your server to work correctly, please remove the 00-AAA file and restore the 00-version file... I believe everything else is correct as it is. Thank you so much for testing!!

**Comment by TechPerplexed** [comment] 2019-11-25 20:20
Thanks! So, if I understand you correctly:

- This time, the file `proxyversion` was created with the content "nginx" (this didn't happen before) and
- The file `version` was created as well with the content 2.2.1 (as before)

However,

- The `00-AAA.yaml` file was not deleted (unlike before) and
- The `00-version.yaml` and `99-network.yaml` were not copied (as before)

That just doesn't make sense! However, as long as you remain the only one with the issue, I am not going to spend hours and hours of troubleshooting - I'm going to assume it's something odd on your side 🤣 

So, for your server to work correctly, please remove the 00-AAA file and restore the 00-version file... I believe everything else is correct as it is. Thank you so much for testing!!

**Comment by Coxeroni** [comment] 2019-11-25 20:22
You understood correctly. Will do as advised. Thanks for your help.

**Comment by TechPerplexed** [comment] 2019-11-26 00:58
I'll close this for now... and fingers crossed we won't have any more issues :)

**Closed by TechPerplexed** 2019-11-26 00:58 UTC
