### ISSUE TITLE
/opt/Gooby gone

### ISSUE THREAD

**Issue by Coxeroni** [TechPerplexed/Gooby#48] opened 2018-11-24 07:22 UTC
It happened to me several times that /opt/Gooby is gone, probably after a reboot where the rclean script deletes it. Seems that then follows an error when Gooby is redownloaded, but I haven't debugged that yet. Only witnessed that it is not there anymore and for example no syncing of the upload folder of mergerfs takes place. Dunno how to solve this...

**Comment by TechPerplexed** [comment] 2018-11-24 19:20
Oh that is odd.... does it only happen after a reboot (not after a manual system clean)? Is it random or does it follow a pattern? I just rebooted and unfortunately I can't reproduce this....... mine came back just fine.  

So the rest of the cron goes through all right? Mount coming back, services started, containers working?

**Comment by Coxeroni** [comment] 2018-11-24 20:01
To be honest I don't know what causes it and when, just saw that rclean does something like that.
I also had some issues with the mounts not coming up and reboots took several minutes. The problem with the mounts was also caused by changes in some of the scripts which were obviously automatically updated but caused trouble. I know this is all very unspecific and probably doesn't help, but acutally I don't know what does what and when so I cannot pin point where to problem is ;)

**Comment by TechPerplexed** [comment] 2018-11-24 21:11
Yes, that is correct - the script will update Gooby and in order to do so, GitHub needs to delete the folder altogether and recreate it. You could change the script not to update Gooby and leave the cron as is... in some ways the cron is necessary to make sure everything comes up in the right order (mount first, containers, next, etc).

You can just edit the file `sudo nano /opt/Gooby/scripts/cron/rclean.sh` and comment out the relevant lines like this:

```
# sudo rm -r /opt/Gooby
# sudo git clone -b master https://github.com/TechPerplexed/Gooby /opt/Gooby 
# sudo chmod +x -R /opt/Gooby/install
# sudo chmod +x -R /opt/Gooby/menus
# sudo chmod +x -R /opt/Gooby/scripts/cron
# sudo rsync -a /opt/Gooby/install/gooby /bin
# sudo chmod 755 /bin/gooby
```

That way Gooby only updates when you run the update function from the menu :)

**Comment by TechPerplexed** [comment] 2018-11-24 21:33
Oh gosh yes, me too!! I haven't heard anyone complain about it though, so I'll leave this open for a few days to see if others chime in having the same problem (or not). It's difficult to troubleshoot what you can't reproduce at all....

**Comment by TechPerplexed** [comment] 2018-11-29 02:04
Seems others don't have the problem Coxeroni, and in the past few days I have been rebooting at least a million times (ok, maybe not quite THAT often, but it feels like it...) and it came back each and every time. I will close it for now and hope you find out what's causing yours to misbehave! Of course you can always add more information to this thread, it won't be locked :)

**Closed by TechPerplexed** 2018-11-29 02:04 UTC

**Comment by HitsvilleUK** [comment] 2018-12-02 05:54
"Seems others don't have the problem"
Oh dear, they do now. :-(
I just set up one of the German servers and Opt/Gooby is gone on each and every reboot.

**Comment by TechPerplexed** [comment] 2018-12-02 16:44
Ha! Ok, for the time being I have disabled the automatic upgrade process (please update Gooby to trigger the update) :) 

Working on a failsafe system to update the menu reliably - to be continued!

**Comment by deedeefink** [comment] 2018-12-02 19:40
Same just happened to me :-(

**Comment by TechPerplexed** [comment] 2018-12-02 19:43
Hmm, that's even stranger... because I disabled the automatic update for now. Please reinstall

```
sudo git clone -b master https://github.com/TechPerplexed/Gooby /opt/Gooby
sudo chmod +x -R /opt/Gooby/install
sudo chmod +x -R /opt/Gooby/menus
sudo chmod +x -R /opt/Gooby/scripts/cron
sudo rsync -a /opt/Gooby/install/gooby /bin
sudo chmod 755 /bin/gooby
```

And then run a system clean and/or reboot. Does it still happen??

**Comment by deedeefink** [comment] 2018-12-02 19:45
Nope, I got the newest version using the snippets above and I still have my folder :-) It just happened one time
