### ISSUE TITLE
Emby metadata 0 byte size

### ISSUE THREAD

**Issue by Coxeroni** [TechPerplexed/Gooby#54] opened 2019-01-29 07:50 UTC
Setup: Emby-beta (4.1.0.1) with mergerfs on Ubuntu 18.04

I let emby create nfos and put them along with the metadata into the folders of the media files. This regularly creates issues, where 0 byte files are created (mostly the nfos) and therefore no information is stored. This does not always happen, but often.

There is no write permission issue, as other files are created successfully and uploaded to google via the cron script. I am writing here, because luke over at emby told me he never saw that issue before and so I suspect that there is something odd with my setup. The respective thread can be found here: https://emby.media/community/index.php?/topic/69069-4101-empty-nfo-files/

Anybody else having these issues and/or knows how to fix this? I am having this issues since several versions, probably right from the beginning...

Edit: I was finally able to reproduce the issue:

0. no nfo present on rclone drive or local drive
1. "search for missing meta data" for item x
2. nfo is created locally and uploaded to rclone drive with > 0 bytes
3. "search for missing meta data" for item x again
4. nfo on rclone drive is 0 byte

So emby seems not to be able to write on the rclone mount, while this works for the user e.g. from command line. I keep asking at the emby forum in parallel to this.

**Comment by TechPerplexed** [comment] 2019-01-29 17:01
Interesting!! I just ran a scan and noticed the same in my setup:

```
2019-01-29 16:05:54.184 Error ProviderManager: Error in metadata saver
	*** Error Report ***
	Version: 4.0.1.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Unix 4.9.0.8
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Processor count: 8
	Program data path: /config
	Application directory: /system
	System.IO.IOException: System.IO.IOException: Illegal seek
	   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
	   at System.IO.FileStream.FlushWriteBuffer()
	   at System.IO.FileStream.Dispose(Boolean disposing)
	   at System.IO.Stream.Close()
	   at NfoMetadata.Savers.BaseNfoSaver.SaveToFile(Stream stream, String path)
	   at NfoMetadata.Savers.BaseNfoSaver.Save(BaseItem item, CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadata(BaseItem item, ItemUpdateType updateType, IMetadataSaver[] savers, CancellationToken cancellationToken)
	Source: System.Private.CoreLib
	TargetSite: Void WriteNative(System.ReadOnlySpan`1[System.Byte])
	   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
	   at System.IO.FileStream.FlushWriteBuffer()
	   at System.IO.FileStream.Dispose(Boolean disposing)
	   at System.IO.Stream.Close()
	   at NfoMetadata.Savers.BaseNfoSaver.SaveToFile(Stream stream, String path)
	   at NfoMetadata.Savers.BaseNfoSaver.Save(BaseItem item, CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadata(BaseItem item, ItemUpdateType updateType, IMetadataSaver[] savers, CancellationToken cancellationToken)
```

I'm wondering if it has something to do with the size or nature of the NFO file and the way MergerFS handles this, since this issue doesn't seem to occur with any other file type.

So yes I can reproduce this (that is good) but I don't know yet what the answer is (that is not so good) 😝

**Comment by Coxeroni** [comment] 2019-01-29 19:08
Thanks for reproducing and chiming in in the emby thread, appreciate it :)

**Comment by TechPerplexed** [comment] 2019-01-29 20:17
It's always nice when a problem is reproducible - it makes troubleshooting easier :) I'm hoping we'll have an answer soon as to the cause - though in all truth I'm not sure if we can solve it. Some of it will depend on the way Rclone, MergerFS and Emby all decide to play nice with us, haha!

**Comment by TechPerplexed** [comment] 2019-01-29 20:37
I never even noticed the log error until you mentioned it - though I did think it was odd that some NFO files were 0k in size (yes, I have had this issue for a long time too, even though I didn't know it). It doesn't seem to harm the viewing experience on Emby or anything else, but still, would be nice if we could get to the bottom of this!

**Comment by Coxeroni** [comment] 2019-01-30 08:19
There is btw a command line method for finding and/or deleting the 0 byte files:

`find ./ -type f -size 0 -print` finds and prints all 0 byte files in the folder and all sub-folders
`find ./ -type f -size 0 -delete` deletes them.

Hope this helps. After Luke's latest answer I have the feeling that out problem is not easy to resolve. In this case I guess I will disable creating the nfos...

**Comment by TechPerplexed** [comment] 2019-01-30 16:47
Thanks! And yes, it seems not much can be done... unless we can convince either MergerFS or Emby to change the procedure (^_^)

I'll close this post in the meantime, since it's not something with an easy solution...

**Closed by TechPerplexed** 2019-01-30 16:47 UTC
Labels: help wanted

**Comment by TechPerplexed** [comment] 2019-02-04 22:23
Going through the yaml file I noticed a tiny error that I never noticed before - the timezone is not taken from the server but hard coded. You might want to find the line

```
- TZ=MNT7
```

and change it to

```
- TZ=${TIMEZONE}
```

**Comment by Coxeroni** [comment] 2019-02-05 08:02
There is an easier way to get the nfos without chainging the mount:

- find and delete all nfos in the folder + subfolders: `find ./ -type f -name "*.nfo" -delete` (check before deleting with -print)
- run a "find missing metadata" in emby and all nfos will be created successfully.

At least this worked for me, dunno if it always works. It should, since no nfo is present so the nfos are written to the local part of the mergerfs and uploaded subsequently.

What does not fit to that theory is, that newly imported files also get a 0 byte nfo although they didn't have any nfo to begin with. So I am still a bit confused about when this happens or not.

**Comment by TechPerplexed** [comment] 2019-02-05 18:51
Yes, it's a strange phenomenon. Glad you found a way to solve it... well... at least somewhat haha. I started with a fresh Emby installation and am currently scanning everything using Rclone instead of MergerFS - probably overkill but at least it works 100% without any errors.
Once the scanning is done I'll switch back to MergerFS and try your method!

**Comment by Coxeroni** [comment] 2019-02-05 19:02
Well you don't need the nfos during daily business if I am not mistaken. So I might run this update procedure before I intend to move the installation or re-setup emby. Another option is to generate the nfo externally, e.g. with [MediaElch](https://www.kvibes.de/mediaelch/) which I could run at my desktop using the rclone mount there. This is probably the way I will go, simply ignoring the issue on a daily basis.

**Comment by TechPerplexed** [comment] 2019-02-05 19:14
Oh nice, thanks for that link - I'll look into it :)
