### ISSUE TITLE
[Question] Sonarr writtable error

### ISSUE THREAD

**Issue by pmscloudeu** [TechPerplexed/Gooby#28] opened 2018-11-07 16:23 UTC
When trying to add existing tv shows and browsing to the corresponding Gdrive folder, I receive the following error: _Folder is not writable by user abc_

**Comment by TechPerplexed** [comment] 2018-11-07 17:08
The folder you need to add is /Media/etc - not your actual mount location. Is that what you tried?

**Comment by pmscloudeu** [comment] 2018-11-07 17:45
Yes, the folder I am trying to add is /Media/TV.

**Comment by TechPerplexed** [comment] 2018-11-07 17:52
What version of Gooby are you running? You might try to uninstall Sonarr (no need to delete user data), run a system clean from the menu (option E - C), then reinstall it again... hopefully that will sort your permission issue.

**Comment by pmscloudeu** [comment] 2018-11-08 07:02
I followed all steps you mentioned above and still receive the same error :(

![sonarr](https://user-images.githubusercontent.com/44649340/48182748-0adfa180-e335-11e8-89f7-3bcb6839d72b.JPG)

**Comment by TechPerplexed** [comment] 2018-11-08 17:05
Hmm, very strange... is Radarr working all right for you? You could try this:

` sudo chown -R $USER:$USER /media/Google`

to see if that gives your user write permissions...

**Comment by bdschuster** [comment] 2018-11-10 07:46
I can confirm the same issue. I imported my old config, and tried to change the root directory, same issue. Tried command above and the folders are still owned by root:root. Anyway to make Sonarr run as root?

**Comment by TechPerplexed** [comment] 2018-11-10 13:02
No, containers can't run as root unfortunately and I can't reproduce the issue myself.

What do you mean by you imported your old config? What version of Sonarr are you using? Is Radarr working all right?

**Comment by bdschuster** [comment] 2018-11-10 14:55
Sorry, imported my old DB (sonarr.db). I'm using Sonarr Beta Version 3.0.0.266. But it appears the user above (from the picture) is using Sonarr Stable, so it doesn't appear to be a version issue. Now mine doesn't appear as blatenly as his does, mine actually doesn't say anything, when I attempt to, add a new series, and I click "add a new path" under root folder, i browse to the Media folder, then TVShows, then hit ok, my root folder goes back to an old path, and it doesn't add the root folder. No indication of any errors, but when I go to the log file, i see:
18-11-10 14:49:17.4|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- Folder is not writable by user abc
I have not tried Radarr. I will install now and let you know. Thanks.

**Comment by TechPerplexed** [comment] 2018-11-10 15:05
Thanks, I just tried it on a fresh installation and it's working fine... so I'm wondering if there is something left in the old database file of yours that still points to the old (non existing) location or something... Just for the heck of it could you try a fresh installation of Sonarr and see if the same happens?

**Comment by bdschuster** [comment] 2018-11-10 15:51
Treid a fresh install, even did a system cleanup before reinstalling. Went to add a series, same thing.
Add series screen:
![image](https://user-images.githubusercontent.com/38221778/48303237-78bed100-e4cd-11e8-95f0-4443d3b06f0a.png)
Browsed to the folder:
![image](https://user-images.githubusercontent.com/38221778/48303240-7d838500-e4cd-11e8-9824-b251987e9253.png)
After Clicking OK, still blank:
![image](https://user-images.githubusercontent.com/38221778/48303241-8411fc80-e4cd-11e8-88a4-f7e4fd732671.png)
Events:
![image](https://user-images.githubusercontent.com/38221778/48303243-8a07dd80-e4cd-11e8-9cdd-cc953d4691a0.png)

Now I did attempt Radarr while I did this as well, and was able to add a Movie with no issues, and no errors in logs.

**Comment by TechPerplexed** [comment] 2018-11-10 16:12
If you type `id youruser`, what are the values given?
E.g. uid=1000(youruser) gid=1000(youruser)

Then when you type `nano /var/local/Gooby/Docker/.env`

Can you confirm that those values match, e.g.

USERID=1000
GROUPID=1000

**Comment by TechPerplexed** [comment] 2018-11-10 16:35
It shouldn't make a difference (my setup is exactly the same)... in fact I don't see anything odd (I assume you edited out your private information such as IP, domain etc).

To rule out any permission issues, please run

sudo chown -R $USER:$USER /var/local/Gooby

Just to be sure :)

**Comment by bdschuster** [comment] 2018-11-10 16:49
Ran command and rebooted to be safe...same thing.
![image](https://user-images.githubusercontent.com/38221778/48303871-dd7e2980-e4d5-11e8-9e74-a1aab8a071d2.png)

If I were to just try and change the TV variable to "/media/Google/TVShows", would i just reboot for it to take effect? I don't know exactly what the variable does.

Any other ideas? I've used Gooby (well, Gooplex) for a while with no issues, but then i had to move my servers, so i decided to install Gooby, and this is the only issue i'm running into so far.

**Comment by TechPerplexed** [comment] 2018-11-10 16:52
Of course you can try it - anything that resolves the issue is worth it!

Sorry you're running into this issue... the only information I can find about it is here: https://forums.sonarr.tv/t/folder-not-writeable-by-user-abc/14072/9
But we've already done all that - all the permissions are correct and "it should just work"... except it doesn't!

**Comment by bdschuster** [comment] 2018-11-10 16:57
How would I make that variable active? Just reboot?

**Comment by bdschuster** [comment] 2018-11-10 17:08
Same thing :-(

**Comment by TechPerplexed** [comment] 2018-11-10 17:12
Waaaaaaaaaaaa, I was afraid of that, but it was worth a try....

Oof I'm not sure what could be your problem... especially since Radarr is working just fine. What happens when you remove Sonarr including the user settings, then install the old version right from scratch? I know that the OP mentioned a problem with that one... but they haven't been back to report any changes so it might be worth a try...

**Comment by bdschuster** [comment] 2018-11-10 17:56
ok, so now this is driving me crazy. I added 
     --gid 1000 --uid 1000 \
     --umask 0 \
To the rclone service, and it mounted as that user "schuster" and has 777 permissions, and bashed into the sonarr container after restarting it, and it as well, has user "abc" as the owner, and 777 permissions. Also went into the Media/TVShows directory and created a folder with no issues. I'm so confused on what's going on here.

**Comment by bdschuster** [comment] 2018-11-10 18:06
So i did what you suggested and I get this (see errors in bold):
Confirm that this is what you named your mount: Gdrive

What is your media folder in Gdrive? (leave empty for root):

**mkdir: missing operand**
**Try 'mkdir --help' for more information.**
**mv: missing destination file operand after '/home/schuster/Downloads'**
**Try 'mv --help' for more information.**
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15    0    15    0     0     10      0 --:--:--  0:00:01 --:--:--    10
done
Created symlink /etc/systemd/system/multi-user.target.wants/gooby.service → /etc/systemd/system/gooby.service.
Created symlink /etc/systemd/system/gooby.service.wants/gooby-rclone.service → /etc/systemd/system/gooby-rclone.service.
Created symlink /etc/systemd/system/gooby.service.wants/gooby-find.service → /etc/systemd/system/gooby-find.service.
Created symlink /etc/systemd/system/gooby.service.wants/mnt-google.mount → /etc/systemd/system/mnt-google.mount.

Done!

**Comment by bdschuster** [comment] 2018-11-10 18:29
FYI, this server is being setup from scratch, so it's not excacly live yet, so this server can be wiped if you need me to. Thanks for everything so far.

**Comment by TechPerplexed** [comment] 2018-11-10 18:52
Ok, if you're setting up the server from scratch, install the "regular" Gooby first:

sudo wget http://bit.ly/GetGooby -O /tmp/install.sh && sudo bash /tmp/install.sh

Then, immediately afterwards (so even before you type "gooby") switch to the new branch by typing those commands as mentioned in the previous message. 

Then go the menu by typing "gooby" and follow all the instructions...

And yes you just got promoted as a beta tester haha!

**Comment by bdschuster** [comment] 2018-11-10 18:58
lol...thanks...and doing this now...won't take long at all...oh, and just an FYI, it doesn't appear your initialization script (on the old one, can't speak for the beta one yet) doesn't appear to install any unzip or 7z...so when installing rclone, or anything for that matter, it fails because it can't find an unzip program. I uinstalled unzip and everything worked as expected.

**Comment by TechPerplexed** [comment] 2018-11-10 19:00
Unzip is installed when you start from scratch :) So yeah that is a vital step... we're bypassing the system right now heh. 

Question: when you setup the system, do you have any "unique" settings such as a custom user path or do you create your user though Gooby from root?

**Comment by bdschuster** [comment] 2018-11-10 19:08
it was from scratch on the currect version (non-beta), and it didn't install...hmmm...no custom user paths, but it's Ubuntu 18.04.1 and i created the user from the install of Ubuntu, not root since root is dsiabled by default in Ubuntu, so gooby didn't ask me for a user. I could create a password for root, after install, and then login as root, and create the user when it asks if you think that will help. I just reinstall Ubuntu, so let me know how you would like me to proceed before installing gooby.

**Comment by TechPerplexed** [comment] 2018-11-10 19:14
No it's fine, I just asked because Gooby takes care of the user creation process if someone runs it from root.  If you are already logged in as a user, it won't ask you to create one.

What provider do you use? And you said it didn't install, what error do you get, still the same?

**Comment by bdschuster** [comment] 2018-11-10 19:17
I didn't get any error during install (unless i wasn't paying attention), i just got an error when i went to install rclone, it said that it needed unzip or 7z installed. so that's what i did and it worked..lol

**Comment by bdschuster** [comment] 2018-11-10 19:59
sooo...First off, unzip didn't install again, so the first install of rclone failed. Installed unzip, reran, worked and installed. I'm assuming you are not mounting to /Media/Google any longer? Cause it's only mounted on /mnt/rclone now. And i tried both Sonarr and Sonarr beta, neither container has gdrive mounted anywhere, so my folders are not there. If you would like to login to my server, i could let you login.

**Comment by TechPerplexed** [comment] 2018-11-10 20:05
Unzip: how weird - it's supposed to install! 😝 

Mount location: you are correct, it didn't make sense the way it was setup in the past. Now all mounts are located in /mnt. The user should not notice this :) But technically, your mount to use is now /mnt/google (please verify that exists and that it has a folder Downloads in addition to what you have on your server). Just ls `/mnt/google` should do the trick but you know that of course :)

Location from within Sonarr/Radarr: this should still be /Media - provided your mount is working correctly you should see your content there!

**Comment by bdschuster** [comment] 2018-11-10 20:08
so /mnt/google doesn't have anything in it, but /mnt/rclone has my files in it. So if the containers are looking back to /mnt/google for /Media, that explains why there is nothing in there.

**Comment by bdschuster** [comment] 2018-11-10 20:31
so, looking at your script to install-rclone, if 18.04 (i have 18.04.1 don't know if that matters), then do "sudo apt-get -y install mergerfs"....when i run that i get:
sudo apt-get -y install mergerfs
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package mergerfs

**Comment by TechPerplexed** [comment] 2018-11-10 20:32
Ahhh ok, now THAT should be installed automatically as well - can you install it this way?

Ok, try this:

```
sudo wget https://github.com/trapexit/mergerfs/releases/download/2.24.2/mergerfs_2.24.2.ubuntu-xenial_amd64.deb -O /tmp/mergerfs.deb
sudo dpkg -i /tmp/mergerfs.d
```
Then follow by:

```
sudo systemctl enable gooby.service gooby-rclone.service gooby-find.service mnt-google.mount
sudo systemctl daemon-reload
sudo systemctl start gooby.service
```

Thanks for your patience - this is good for me to know too :)

**Comment by bdschuster** [comment] 2018-11-10 20:38
ok, that works, and files are now in /mnt/google....now another piece of information, going back to unzip not installing, i looked at your install script for gooby, if i run manually i get:
schuster@admin:/opt/Gooby/install$ sudo apt-get -y install \
>         git \
>         fail2ban \
>         nano \
>         unzip \
>         wget \
>         curl \
>         ufw \
>         socat \
>         fuse \
>         apt-transport-https \
>         acl \
>         ca-certificates \
>
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'apt' instead of 'apt-transport-https'
E: Unable to locate package fail2ban

So the script stops on fail2ban....so it never gets to anything after. Did Ubuntu take a bunch out out of their repository recently?

**Comment by TechPerplexed** [comment] 2018-11-10 20:41
Wow that is indeed very strange. I tested this new setup on a Hetzner cheap server - both with 16.04 and 18.04 and neither reported any difficulties. 

But yeah this might explain why you are running into so many issues!

**Comment by bdschuster** [comment] 2018-11-10 20:43
also back to Sonarr (stable version) 
![image](https://user-images.githubusercontent.com/38221778/48305796-ec290880-e4f6-11e8-9302-56a458b3ba47.png)

**Comment by TechPerplexed** [comment] 2018-11-10 20:46
GAHHHH after all that!!! I'm sorry, I am out of options... for now. It should work yet it doesn't, grr!! Let me do some more research on this!

**Comment by bdschuster** [comment] 2018-11-10 20:50
tell you what. Let me install 16.04.3 and see what happens here. I'll BRB.

**Comment by TechPerplexed** [comment] 2018-11-10 20:53
Thanks :) I'm also working on a version that won't halt with missing packages... just saved (but obviously not tested) - let me know if it proceeds!

**Comment by bdschuster** [comment] 2018-11-10 21:34
Soooo....I can tell you that the install went MUCH smoother....all packages installed no issues at all...mounts are all good...everything.....EXCEPT, still getting the folder not writable by abc again :-( 
I can confirm from the sonarr container that i can create a file in TVShows as root, but I can't switch to user "abc" in a container to test.

**Comment by TechPerplexed** [comment] 2018-11-10 21:50
First of all: thank you so much for being a willing victim here :) I appreciate your patience and extensive testing - when this update goes live, it should benefit everyone.

That said, I'm so sorry you are still having this pesky permission issue! I'll do some research and hoping to come up with an answer - can't let a little abc get us down right? 😆

**Comment by TechPerplexed** [comment] 2018-11-10 22:06
Oh it's driving me crazy too! No I don't have the problem, and I know several people who run the server on the "new Gooby" (not the new new as you have been testing) without any issues whatsoever. I just have a regular Gsuite account, no team drive.

What is even weirder: you Radarr works fine. Those two packages are basically clones of each other! You'd expect if one fails, the other would too. 

I also tested with a free account and a few movies/series because I don't run my libraries on the root of Gdrive, I use a folder /Media that contains my movies, tv shows etc. But no matter what I try to break, I'm unable to.

There isn't much information available on the Internet either, only thing I could find was this: https://forums.sonarr.tv/t/folder-not-writeable-by-user-abc/14072/9 - yeah, not altogether helpful and just confirms all your settings/permissions are fine.

Let's race each other in trying to find a solution 🤣 

Have a great weekend, cheers, Sophia

**Comment by bdschuster** [comment] 2018-11-10 23:12
OMFG! I just figured it out, and it wasn't the scripts at all! I'm so angry it was so stupid, and it's all Sonarr's fault! lol
Soooo...Sonarr and Radarr send a text file called "sonarr_write_test.txt"/"radarr_write_test.txt" to verify write, then removes the file. At one point. not sure when, the file wasn't removed after it was created, and the permissions on it were for an old API email i used when testing out Plexguide. (I love yours a lot better, not a fan of PGBlitz, it caused a lot of bandwidth on Sonarr/Radarr scans because it had to download the file then re-upload it). Anwyays, I deleted the file using drive WebGUI, and like magic, I can  add the path to Sonarr again! I'm so angry and happy at the same time.

**Comment by bdschuster** [comment] 2018-11-10 23:16
I had this happen one time years ago on physical disks...like 3-4 years ago...and i don't know why i thought of it...but i'm glad i did.

**Comment by TechPerplexed** [comment] 2018-11-10 23:32
Hahahaha I'm so happy you found the culprit!!! Normally I would have given you 3 slaps with a wet noodle, but since you have been SO helpful in testing my new setup, I'll give you some virtual flowers instead 🌹 🌷 🌹

I'll close this thread now - thanks for reporting back!

**Closed by TechPerplexed** 2018-11-10 23:32 UTC
