### ISSUE TITLE
rclone upload issues + errors after vps restart

### ISSUE THREAD

**Issue by verycoolm8** [TechPerplexed/Gooby#120] opened 2020-03-10 22:45 UTC
Hi guys,

First just wanted to say thank you for creating such an easy process to get all this going.
I have had it running pretty well for the past two weeks or so but yesterday Plex froze, then so did everything else which led me to do a quick restart, that's when things started to get weird.

After the restart all of the additional services, Sonarr, Radarr, Organizr would not work. I did a clean up and then another restart and they came back online and so far so good.

But rclone also seems to have perished somewhere along the way if i check /mnt/ I see 

- google (has drive items but also a Downloads folder that directs me to the /uploads/Downloads?)
- local (empty)
- rclone (has several items that are on my drive in there)
- uploads (uploads > downloads with Drive items)

But nothing is uploading. I have a few downloads in the /uploads/downloads folder but they have been sitting there since yesterday and a triggering uploads does nothing.

I have reinstalled rclone several times and deleted the remote and remade, updated gooby, system clean ups etc. I'm just not sure what's wrong & if my /mnt/ subfolders are even set up correctly as there seems to be a lot of duplicate stuff + nothing uploading.

Plex was also telling me to check if the drive was mounted as it couldn't find the folder but that error seems to have resolved itself. I can now play on a desktop but any mobile devices give me a check server error (not sure if related?)

EDIT: Also just to add fuel to the fire, I tried restarting the VPS earlier to see if that fixed the uploading issue and have just checked back in on it, Gooby doesn't think half of the apps are installed (I had everything installed) & I can no longer view them by using menu.mydomain.xyz, sonarr.mydomain.xyz etc.

STATUS                          : NAMES
Up About a minute (healthy)     : deluge
Up About a minute (healthy)     : ombi
Up About a minute (healthy)     : plex
Up About a minute (unhealthy)   : jackett

Anything I can do to help diagnose these issues would be appreciated. Thanks!

**Comment by TechPerplexed** [comment] 2020-03-11 16:43
Apologies for the late reply, life's been a bit hectic. 

So, first of all, your folders seem okay. It's by default that Downloads appears both in your home folder and in /mnt/uploads, so no worries there.

Just to confirm before any further troubleshooting, when you run `rclean`, does it finish without any errors?

**Comment by TechPerplexed** [comment] 2020-03-11 17:18
WAIT you have to change something else as well, otherwise your settings won't take.

Change

`- ${CONFIGS}/EmbyStat:/app/config`

to

`- ${CONFIGS}/EmbyStat:/config`

That should do it!

**Comment by verycoolm8** [comment] 2020-03-11 23:44
Hello! No problem at all, `rclean` finishes without error.

**Comment by verycoolm8** [comment] 2020-03-12 00:57
Okay so after doing the rclean, it uploaded the files I had previously downloaded but in Plex the Library was empty. So I edited the folders and in Media I don't have any sub-folders to choose from. 

[https://i.imgur.com/pfGbAkO.png](url)

Then in gooby it shows this.

https://i.imgur.com/YvK2tlF.png

and finally in my /mnt/google/Movies folder it now only shows the new items it uploaded after doing `rclean` & not the other items on my drive (but those files that were stuck before the rclean definitely synced to Gdrive)

Sorry about all this! Hopefully we can get it working again.

**Comment by TechPerplexed** [comment] 2020-03-12 01:08
Ok that looks promising :) What do you get when you type  `ls /mnt/google` ?

**Comment by verycoolm8** [comment] 2020-03-12 01:14
That's what I like to hear :)

I get ` Downloads   Movies  'TV Shows' `

**Comment by TechPerplexed** [comment] 2020-03-12 01:15
Ok, so just to confirm, then when you type `ls /mnt/google/Movies` you get a list of your movies, right?

**Comment by verycoolm8** [comment] 2020-03-12 01:15
Yep!

**Comment by TechPerplexed** [comment] 2020-03-12 01:17
In that case, Plex has no choice but to show your movies in Media 😆 (the link in your first image). If you don't see your movies and TV shows folder there, run another rclean to trigger it - something might have changed when you edited a folder.

**Comment by TechPerplexed** [comment] 2020-03-12 01:21
Oh wait, I missed what you said earlier, after your edit:

> and finally in my /mnt/google/Movies folder it now only shows the new items it uploaded after doing rclean & not the other items on my drive (but those files that were stuck before the rclean definitely synced to Gdrive)

I need to know for sure that `ls /mnt/google/Movies` shows ALL your movies, not just the new ones.

What do you get when you type `ls /mnt/rclone/Movies`? That should match the google folder...

**Comment by verycoolm8** [comment] 2020-03-12 01:34
`rclean` is magical. The folders all appearing in Plex now & media has returned. 
Both `ls /mnt/google/Movies` & `ls /mnt/rclone/Movies` display the same information. Thank you!!

Also just one other question, should the files in /Downloads/ automatically delete once uploaded or is this something I have to do manually? It looks like a lot of the .torrent files and completed files are still sitting in there or perhaps they will eventually delete now that everything seems to be working properly.

**Comment by TechPerplexed** [comment] 2020-03-12 01:41
Yay, yes rclean (or system clean from the menu, which is the same thing) usually corrects a multitude of problems 😄 

As for your question, usually downloads are deleted fully automatically once they are processed by Deluge. However I noticed that it is a bit slow lately, and Deluge doesn't always delete files afterwards. Once they are gone from Deluge though, they should definitely vanish from your Downloads folder!
Are you saying yours is behaving differently?

**Comment by verycoolm8** [comment] 2020-03-12 07:49
Yeah doesn't seem to be deleting automatically. Basically Ombi -> Sonarr -> Deluge works Instantly. Then the movie downloads and just sits on 'Queued 100.00% not leaving Deluge until I manually remove it.

I also spoke too soon the uploading has dropped off again. I have ran a few rcleans and can't get them to upload automatically again. 1 or 2 files will upload after every rclean but most aren't doing anything. Previously it would take about 10 - 15 minutes for a request from Ombi to appear in Plex.
I'm so lost, everything was working perfectly up until a day or so ago and now things are breaking everywhere :(

**Comment by TechPerplexed** [comment] 2020-03-12 16:24
Hmm, strange... you said you made some changes to your folders - can you elaborate what exactly you edited? I have never heard of anything throttling uploads (except the 750G limit of Google).

Also, nothing in the Downloads folder will upload by design, because that would mean it would upload all your partial files from the torrents and would create chaos.
It's after you (or probably Sonarr/Radarr) moves them to the designated folder that the uploads should kick in.

**Comment by verycoolm8** [comment] 2020-03-13 00:01
In my Google drive? I haven't edited any folders They are setup Plex -> Movies & Plex -> TV Shows
So last night a few movies decided to upload but not delete and my VPS was full. I tried to `rclean` but it kept giving me these errors.

`Cleaning mount leftovers

mountpoint: /mnt/rclone: Transport endpoint is not connected
mountpoint: /mnt/google: No such file or directory
chown: cannot access '/mnt/rclone': Transport endpoint is not connected

Calling on Upgrade Service

Your system has already been upgraded to v2.2.1... skipping upgrade

```
/opt/Gooby/scripts/cron/upgradeservice.sh: line 109: echo: write error: No space left on device
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    13  100    13    0     0     31      0 --:--:-- --:--:-- --:--:--    31
/opt/Gooby/install/misc/environment-build.sh: line 23: cannot create temp file for here-document: No space left on device
cat: write error: No space left on device
done
Job for rclonefs.service failed because the control process exited with error code.
See "systemctl status rclonefs.service" and "journalctl -xe" for details.
Job for mergerfs.service failed because the control process exited with error code.
See "systemctl status mergerfs.service" and "journalctl -xe" for details.
mountpoint: /mnt/rclone: Transport endpoint is not connected
mountpoint: /mnt/google: No such file or directory
Waiting on mounts to be created...
mountpoint: /mnt/rclone: Transport endpoint is not connected
mountpoint: /mnt/google: No such file or directory
Waiting on mounts to be created...`
```

So I manually deleted the Files from the Downloads folder that I knew were on Gdrive, uninstalled & reinstalled `rclone` and did another `rclean` which seemed to work fine.

So is there any particular settings you can think of that would be causing the Files to not delete?
& Why rclone just seems to drop off now.. I'm assuming other people don't have to be fixing their stuff daily with `rclean` ?

**Comment by bdschuster** [comment] 2020-03-13 00:26
I don't have this issue at all. Was everything working before this whole VPS reboot? Have you, since it's been back up, been able to see your media from Google at all? What VPS are you using, and what version of linux? Sorry, i'm a troubleshooter, need to see where this may be causing an issue.

**Comment by verycoolm8** [comment] 2020-03-13 00:36
Yeah everything was working well before I had to restart the VPS when all the Gooby apps wouldn't load. I had a few instances of Rclone losing the mount or something but for around 3 weeks it worked as I imagine you guys intended, very seamlessly. 

Yeah off an on, as mentioned in the previous posts it will work then stop, will lose Rclone, will uninstall rclone it works for a bit then dies again it just doesn't work properly anymore.

I'm using an Australian VPS https://obble.com.au/products-vps wth their $80 p/m plan.
Running ubuntu-18.04-x86_64.

Thanks!

**Comment by bdschuster** [comment] 2020-03-13 01:00
So weird. I don't know why it would be dropping out like that, and your VPS doesn't seem to mention that they block fuser mount or anything, but I have had issues with Ubuntu 18.04 in the past, what's why i moved to Debian, haven't had any issues since. Ubuntu tries to add more security crap that screws a lot up. I'm not sure where to tell you to look next, or maybe if you could just start from scratch and see where that lands you. @TechPerplexed , any other ideas?

**Comment by TechPerplexed** [comment] 2020-03-13 01:32
I'm baffled as well, it almost seems as if your provider randomly drops support for FUSE (that is usually what causes the "transport endpoint not connected" errors).

Usually when rclean sorts a problem, Rclone remains stable as a rock. I can't honestly remember the last time I rebooted my server, and I don't think it's ever dropped the mount spontaneously. You sure pay enough for your provider, you'd expect a little better service than that!

Would it be possible for you to rebuild your server on Debian as @bdschuster suggested?

**Comment by verycoolm8** [comment] 2020-03-13 03:57
I feel a little better that you guys are as stumped as me 😆 
I'll rebuild it on Debian and see how we go, hopefully this sorts the issue if not i'll take it up with the VPS provider as it's a bit strange that everything has started to fall apart without any changes from me.

Is there anyway to save any type of Gooby configuration to speed up the reconfiguration process or best to just wipe it all and start fresh to avoid any potential conflicts?

**Comment by verycoolm8** [comment] 2020-03-13 11:27
Hey guys. Did a reinstall with Debian and set up the Basics for now Ombi - Sonarr - Deluge & Plex for testing (+rclone) 

Things look better, files are uploading and moving automatically after download with Deluge eventually deleting. Only thing that is messing up is once downloaded the Files aren't being put in the correct folder, they are moving to the root folder of my Gdrive. I'm assuming it's Radarr?

![image](https://user-images.githubusercontent.com/62038160/76616932-4289d980-6579-11ea-8dc3-8b79cf22ef67.png)

Should I change that path to /Media/Movies & Media/TV for Sonarr? Just not sure if that's what handles this part of the process (as it says /Media on the wiki) and not keen on changing settings unless i'm 100% after the recent issues 😆

**Comment by TechPerplexed** [comment] 2020-03-13 17:22
Yes, you will need to change your root folder to /Media/Movies (or TV), otherwise Radarr/Sonarr will indeed place them all directly in /Media. Glad things are looking better!

**Comment by verycoolm8** [comment] 2020-03-14 08:37
Awesome. Thank you guys, everything working perfectly again.

**Comment by TechPerplexed** [comment] 2020-03-15 12:01
Awesome, glad to hear it! As for the error, try analyzing the video manually - after the rebuild it probably still needs to update things behind the scenes. Will close this for now... feel free to add additional comments though :)

**Closed by TechPerplexed** 2020-03-15 12:01 UTC
