### ISSUE TITLE
Upgrade to v2.2.1 Didn't Work

### ISSUE THREAD

**Issue by mr-handerson** [TechPerplexed/Gooby#115] opened 2019-12-01 01:05 UTC
So I had some time this weekend so I thought I'd try to update. Here's what happened.
Created a fresh backup before starting - OK
Ran an update Gooby, said it was successful.
Ran a System cleanup - says I will need to install and configure rclone first... hmm
Checked Environment - server name, proxy version and gooby version are all blank
Tried to update Gooby again - fatal: repository '/opt/.Gooby' does not exist
D'oh
Rebooted server
Nothing started back up after reboot
Tried to update Gooby - same error
System cleanup - still says install rclone
Checked environment, server name and gooby version are now listed but proxy version is blank
OK, so I'll install rclone like it's telling me to
Says latest version is already installed and detects my remote as it has been setup previously
Chose quit, confirmed mount name as previously named and media folder on google
Then got the following:

> cat: /var/local/Gooby/Docker/.config/cf_email: No such file or directory
cat: /var/local/Gooby/Docker/.config/cf_key: No such file or directory
cat: /var/local/Gooby/Docker/.config/goobybranch: No such file or directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    13  100    13    0     0    110      0 --:--:-- --:--:-- --:--:--   110
cat: /var/local/Gooby/Docker/.config/proxyversion: No such file or directory
done

and it didn't exit back to the Gooby menu
Had to ctrl+Z to stop it
Saw that something similar to the above error had been mentioned in #114 so tried that fix
rclean ran but with a lot of errors but eventually said it finished
Check Environment is now fully populated
However, nothing is running
Checked installed apps - EMPTY - sadness
Ran rclean again so that I could capture the errors

> Shutting everything down
ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for portainer: 'depends_on'
Unsupported config option for netdata: 'depends_on'
Unsupported config option for radarr: 'depends_on'
Unsupported config option for radarr4k: 'depends_on'
Unsupported config option for tautulli: 'depends_on'
Unsupported config option for nzbget: 'depends_on'
Unsupported config option for sonarr: 'depends_on'
Unsupported config option for letsencrypt-nginx-proxy-companion: 'healthcheck'
Unsupported config option for nginx-proxy: 'healthcheck'
Unsupported config option for ombi: 'healthcheck'
Unsupported config option for plex: 'healthcheck'

Then later

> Updating and starting containers
ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for portainer: 'depends_on'
Unsupported config option for letsencrypt-nginx-proxy-companion: 'healthcheck'
Unsupported config option for nginx-proxy: 'healthcheck'
Unsupported config option for ombi: 'healthcheck'
Unsupported config option for plex: 'healthcheck'
Unsupported config option for nzbget: 'healthcheck'
Unsupported config option for sonarr: 'healthcheck'
Unsupported config option for netdata: 'healthcheck'
Unsupported config option for radarr: 'healthcheck'
Unsupported config option for radarr4k: 'healthcheck'
Unsupported config option for tautulli: 'healthcheck'
ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for portainer: 'depends_on'
Unsupported config option for letsencrypt-nginx-proxy-companion: 'healthcheck'
Unsupported config option for nginx-proxy: 'healthcheck'
Unsupported config option for ombi: 'healthcheck'
Unsupported config option for plex: 'healthcheck'
Unsupported config option for netdata: 'healthcheck'
Unsupported config option for radarr: 'healthcheck'
Unsupported config option for radarr4k: 'healthcheck'
Unsupported config option for tautulli: 'healthcheck'
Unsupported config option for nzbget: 'healthcheck'
Unsupported config option for sonarr: 'healthcheck'

Found #113 
00-version.yaml did not exist in /var/local/Gooby/Docker/components
Copied it over
Ran rclean again

>Shutting everything down
ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for portainer: 'depends_on'
Unsupported config option for netdata: 'depends_on'
Unsupported config option for radarr: 'depends_on'
Unsupported config option for radarr4k: 'depends_on'
Unsupported config option for tautulli: 'depends_on'
Unsupported config option for nzbget: 'depends_on'
Unsupported config option for sonarr: 'depends_on'
Unsupported config option for letsencrypt-nginx-proxy-companion: 'healthcheck'
Unsupported config option for nginx-proxy: 'healthcheck'
Unsupported config option for ombi: 'healthcheck'
Unsupported config option for plex: 'healthcheck'

But after that it pulled and created everything properly and everything came online.
Ran a final rclean to test, worked as expected now.
Did a reboot to test everything came back online - it did. So all seems to be back up and running.
Will be trying out the new backup shortly, plus testing that downloads, rclone uploads etc. all work

Feel free to close once viewed; I thought the feedback may be useful

**Comment by bifa2** [comment] 2019-12-01 13:05
I think I'm having problems related to this also. Last night I was streaming from Plex ok. Today, it complained about the drive with media on not being mounted. I logged into the server, ran `Gooby` and tried to do an update but it moaned about the disk being full just like is mentioned in #114. `df` confirmed this. I rebooted the server, and it was back to 30% used (so it had *really* filled up, somehow). However running `Gooby` it says the command can't be found. 

Does Gooby attempt to autoupdate?

**Comment by bifa2** [comment] 2019-12-01 14:07
After this, `rclean` gave exactly the same errors as above.

```
cp /opt/Gooby/scripts/nginx/00-version.yaml /var/local/Gooby/Docker/components
rclean
```

Gave:

```
Shutting everything down

ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for letsencrypt-nginx-proxy-companion: 'healthcheck'
Unsupported config option for nginx-proxy: 'healthcheck'
Unsupported config option for plex: 'healthcheck'
Unsupported config option for netdata: 'healthcheck'
Unsupported config option for tautulli: 'healthcheck'
```
... It pulled and spun up the containers but Plex was reporting unavailable. Ran `rclean` a second time. 'Shutting everything down' didn't error, but Plex still unavailable. Rebooted, and containers not started. `rclean` and got:

```Updating Gooby

fatal: repository '/opt/.Gooby' does not exist
```

and also some error about docker_default having active endpoints. Also more errors saying...

```
cat: /var/local/Gooby/Docker/.config/cf_email: No such file or directory
cat: /var/local/Gooby/Docker/.config/cf_key: No such file or directory
cat: /var/local/Gooby/Docker/.config/goobybranch: No such file or directory
cat: /var/local/Gooby/Docker/.config/proxyversion: No such file or directory
```

Thanks @mr-handerson for providing so much detail. Very helpful. I'm stuck now, so may restore from a backup of the VM but expect I'll just hit the same issue when Gooby autoupdates again.

**Comment by bifa2** [comment] 2019-12-01 15:01
I've made it worse by uninstalling Plex (with choosing to preserve settings) and reinstalling it. `rclean`. Plex won't show anything now (webpage times out). Rebooted, still not up. I think I'm going to attempt a rollback to a VM snapshot from 2 days ago.

**Comment by TechPerplexed** [comment] 2019-12-01 15:59
I don't think you need to rollback... honestly the updates aren't more exciting than a few changed locations and improvements. We can sort you out :)

Can you follow these suggestions first please and report back?

```
rm /var/local/Gooby/Docker/.config/version
rclean
```

See also issue #114

**Comment by TechPerplexed** [comment] 2019-12-01 16:01
Also, thanks @mr-handerson for the detailed feedback!

**Comment by bifa2** [comment] 2019-12-01 16:02
I rolled back, booted up to get the same issue as I started the day with. 

```
rm /var/local/Gooby/Docker/.config/version
```
gave permission denied. Ran it with sudo, then `rclean`.

We're back to the same errors as before though:

```
Updating Gooby

fatal: repository '/opt/.Gooby' does not exist

Shutting everything down

ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for netdata: 'depends_on'
Unsupported config option for tautulli: 'depends_on'
Unsupported config option for letsencrypt-nginx-proxy-companion: 'healthcheck'
Unsupported config option for nginx-proxy: 'healthcheck'
Unsupported config option for plex: 'healthcheck'
```

Gooby thinks rclone isn't installed, etc.

**Comment by TechPerplexed** [comment] 2019-12-01 16:19
Let's help the upgrade a little manually (yeah I know that's technically a cheat but if it works, it works) 😄 

Run the following commands:

```
sudo mkdir -p /var/local/Gooby/Docker/.config
sudo chown -R ${USER}:${USER} /var/local/Gooby/Docker
echo "master" > /var/local/Gooby/Docker/.config/goobybranch
echo "nginx" >  /var/local/Gooby/Docker/.config/proxyversion
echo " " >  /var/local/Gooby/Docker/.config/version

```

Then run rclean again... make sure it's not still running (if so, you will need to kill the process).

How's that work?

**Comment by bifa2** [comment] 2019-12-01 16:56
I went back to the state at which you said no need to restore (where I could not access Plex at all). Ran the commands you suggested (though I don't know how to check for, or kill the rclean process). 

```
Cleaning mount leftovers
mountpoint: /mnt/rclone: No such file or directory
mountpoint: /mnt/google: No such file or directory
```
Sadly Plex still won't load at all.

**Comment by bifa2** [comment] 2019-12-01 17:17
I'm so confused at this point. 

So https://mydomain.com:32400 was how I'd access the Plex server previously. This was intentional, as port 32400 is opened in the firework where I run the server. To get this working, I'd changed the following files:
```
/var/local/Gooby/Docker/docker-compose.yaml
```
and possibly another yaml file but I can't find it (learning the locations of files on Linux seems to break my brain), and I believe I'd changed a port within the Plex web interface also.

Plex is now totally unresponsive on 32400, but I can get a web interface to load on 8443. I guess this was reset during the uninstall and reinstall of Plex, but I can't access the server settings (because it says server unavailable) in order to change it.

I can find a reference to 8443 in `/var/local/Gooby/Plex/Library/Application Support/Plex Media Server/Preferences.xml` - do you think stopping the Plex container and editing this, and starting it again, might restore access on the correct port at least? As for why the 'server is unavailable'... still stumped.

**Comment by bifa2** [comment] 2019-12-01 17:32
Changing the preferences.xml made no difference. As I've spent about 4 hours of my Sunday trying to sort this, I'm at the point where I just want to restore a snapshot from a week ago and be done with it. Is it possible to block the automatic upgrade of Gooby please? If I revert the snapshot, the VM will boot and I'm concerned it'll attempt to upgrade on boot. If that's the case, perhaps disconnecting the NIC, accessing the VM console session and disabling within the VM is an option... if there is a way.

**Comment by TechPerplexed** [comment] 2019-12-01 17:58
As I said, you are making way too much of the upgrade... it's just that some files have a new location. Once we sort that, everything should work just the way it did before. Nothing was changed that would hamper your modifications of Plex or any other container, except you uninstalled it so when you reinstall, it reverts back to the original for obvious reasons. IF you really feel the need to tinker with ports later, you will need to change the file in components, not the docker-compose.yaml file since that will be overwritten by the file in components. But we digress... let's get you up and running first. Don't tinker until the basics work... 

So. First things first. When you run rclean after you follow the instructions I posted above, what happens EXACTLY? At what point do you get errors, does it stop, etc?

**Comment by bifa2** [comment] 2019-12-01 22:03
Output of rclean:

```
Updating Gooby

fatal: repository '/opt/.Gooby' does not exist

Shutting everything down

ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for letsencrypt-nginx-proxy-companion: 'healthcheck'
Unsupported config option for nginx-proxy: 'healthcheck'
Unsupported config option for plex: 'healthcheck'
Unsupported config option for netdata: 'healthcheck'
Unsupported config option for tautulli: 'healthcheck'

Updating Rclone if possible

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4437  100  4437    0     0   120k      0 --:--:-- --:--:-- --:--:--  120k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15  100    15    0     0    384      0 --:--:-- --:--:-- --:--:--   384

The latest version of rclone rclone v1.50.2 is already installed.


Cleaning mount leftovers

mountpoint: /mnt/rclone: No such file or directory
mountpoint: /mnt/google: No such file or directory

Calling on Upgrade Service

Upgrading to v2.2.1... just a moment

15 2 * * SUN /opt/Gooby/scripts/cron/backup.sh > /dev/null 2>&1
10 2 1 * * /bin/resetbackup > /dev/null 2>&1

Upgrade to v2.2.1 complete... prodeeding

cat: /var/local/Gooby/Docker/.config/cf_email: No such file or directory
cat: /var/local/Gooby/Docker/.config/cf_key: No such file or directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0    112      0 --:--:-- --:--:-- --:--:--   112
done

Updating and starting containers

ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for letsencrypt-nginx-proxy-companion: 'healthcheck'
Unsupported config option for nginx-proxy: 'healthcheck'
Unsupported config option for plex: 'healthcheck'
Unsupported config option for netdata: 'healthcheck'
Unsupported config option for tautulli: 'healthcheck'
ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for netdata: 'depends_on'
Unsupported config option for tautulli: 'depends_on'
Unsupported config option for letsencrypt-nginx-proxy-companion: 'healthcheck'
Unsupported config option for nginx-proxy: 'healthcheck'
Unsupported config option for plex: 'healthcheck'

Cleaning Docker leftovers

Total reclaimed space: 0B

Patching server

Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic-security InRelease
Hit:5 https://download.docker.com/linux/ubuntu bionic InRelease
Hit:6 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Sun Dec  1 22:02:35 UTC 2019 - Done! Your system should be back online
```

No containers are started.

**Comment by TechPerplexed** [comment] 2019-12-01 22:31
Great :) I mean, yes please don't perform any additional roll backs, edits, snapshots or upgrades from now on. We'll work from this version that previously worked until we get you sorted ^_^ 

Let's try this:

```
sudo rm -r /opt/Gooby > /dev/null 2>&1
sudo git clone -b master https://github.com/TechPerplexed/Gooby /opt/Gooby
sudo chmod +x -R /opt/Gooby/install
sudo chmod +x -R /opt/Gooby/menus
sudo chmod +x -R /opt/Gooby/scripts/bin
sudo chmod +x -R /opt/Gooby/scripts/cron
rm /var/local/Gooby/Docker/.config/version
```

Then run rclean. Do you still get those same errors?

**Comment by TechPerplexed** [comment] 2019-12-01 22:38
To speed things up, I'll post the next steps. If you still get errors, please check this folder:

`ls /var/local/Gooby/Docker/components`

It should NOT contain a file named `00-AAA.yaml`

It SHOULD contain two files named `00-version.yaml` and `01-proxy.yaml`

If it doesn't, do this:

```
sudo rsync -a /opt/Gooby/scripts/nginx/{00-version.yaml,01-proxy.yaml,99-network.yaml} /var/local/Gooby/Docker/components
sudo rm /var/local/Gooby/Docker/components/00-AAA.yaml
```

Check if the files are now there, and the AAA file is removed, then run rclean again...

Results?

**Comment by bifa2** [comment] 2019-12-01 23:21
Thanks for the multi-post. That worked and we're back. Just for full detail:

I ran the lines from the first reply (starting with `sudo rm -r /opt/Gooby > /dev/null 2>&1` and got:

```
Updating Gooby

Cloning into '/opt/.Gooby'...
remote: Enumerating objects: 65, done.
remote: Counting objects: 100% (65/65), done.
remote: Compressing objects: 100% (65/65), done.
remote: Total 12405 (delta 28), reused 0 (delta 0), pack-reused 12340
Receiving objects: 100% (12405/12405), 2.19 MiB | 3.81 MiB/s, done.
Resolving deltas: 100% (8431/8431), done.

Shutting everything down

ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for netdata: 'depends_on'
Unsupported config option for tautulli: 'depends_on'
Unsupported config option for letsencrypt-nginx-proxy-companion: 'healthcheck'
Unsupported config option for nginx-proxy: 'healthcheck'
Unsupported config option for plex: 'healthcheck'

Updating Rclone if possible

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4437  100  4437    0     0  92437      0 --:--:-- --:--:-- --:--:-- 92437
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15  100    15    0     0    312      0 --:--:-- --:--:-- --:--:--   312

The latest version of rclone rclone v1.50.2 is already installed.


Cleaning mount leftovers

mountpoint: /mnt/rclone: No such file or directory
mountpoint: /mnt/google: No such file or directory

Calling on Upgrade Service

Upgrading to v2.2.1... just a moment

15 2 * * SUN /opt/Gooby/scripts/cron/backup.sh > /dev/null 2>&1
10 2 1 * * /bin/resetbackup > /dev/null 2>&1

Upgrade to v2.2.1 complete... prodeeding

cat: /var/local/Gooby/Docker/.config/cf_email: No such file or directory
cat: /var/local/Gooby/Docker/.config/cf_key: No such file or directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0     36      0 --:--:-- --:--:-- --:--:--    36
done

Updating and starting containers

ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for letsencrypt-nginx-proxy-companion: 'healthcheck'
Unsupported config option for nginx-proxy: 'healthcheck'
Unsupported config option for plex: 'healthcheck'
Unsupported config option for netdata: 'healthcheck'
Unsupported config option for tautulli: 'healthcheck'
ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for netdata: 'depends_on'
Unsupported config option for tautulli: 'depends_on'
Unsupported config option for letsencrypt-nginx-proxy-companion: 'healthcheck'
Unsupported config option for nginx-proxy: 'healthcheck'
Unsupported config option for plex: 'healthcheck'

Cleaning Docker leftovers

Total reclaimed space: 0B

Patching server

Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Hit:3 https://download.docker.com/linux/ubuntu bionic InRelease
Get:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Hit:6 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease
Fetched 252 kB in 1s (398 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Sun Dec  1 23:11:08 UTC 2019 - Done! Your system should be back online

Restoring permissions... this could take a few minutes
```

Executing `ls /var/local/Gooby/Docker/components` showed it was *missing* `00-version.yaml` only. Ran the other commands to restore files, confirmed that there was no `00-AAA.yaml` and that `00-version.yaml` and `01-proxy.yaml` were there. 

Ran rclean once more as required and got:

```
Updating Gooby

Cloning into '/opt/.Gooby'...
remote: Enumerating objects: 65, done.
remote: Counting objects: 100% (65/65), done.
remote: Compressing objects: 100% (65/65), done.
remote: Total 12405 (delta 28), reused 0 (delta 0), pack-reused 12340
Receiving objects: 100% (12405/12405), 2.19 MiB | 3.80 MiB/s, done.
Resolving deltas: 100% (8431/8431), done.

Shutting everything down

ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for letsencrypt-nginx-proxy-companion: 'healthcheck'
Unsupported config option for nginx-proxy: 'healthcheck'
Unsupported config option for plex: 'healthcheck'
Unsupported config option for netdata: 'healthcheck'
Unsupported config option for tautulli: 'healthcheck'

Updating Rclone if possible

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4437  100  4437    0     0   131k      0 --:--:-- --:--:-- --:--:--  131k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15  100    15    0     0    405      0 --:--:-- --:--:-- --:--:--   405

The latest version of rclone rclone v1.50.2 is already installed.


Cleaning mount leftovers

mountpoint: /mnt/rclone: No such file or directory
mountpoint: /mnt/google: No such file or directory

Calling on Upgrade Service

Upgrading to v2.2.1... just a moment

15 2 * * SUN /opt/Gooby/scripts/cron/backup.sh > /dev/null 2>&1
10 2 1 * * /bin/resetbackup > /dev/null 2>&1

Upgrade to v2.2.1 complete... prodeeding

cat: /var/local/Gooby/Docker/.config/cf_email: No such file or directory
cat: /var/local/Gooby/Docker/.config/cf_key: No such file or directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0    110      0 --:--:-- --:--:-- --:--:--   110
done

Updating and starting containers

Pulling nginx-proxy                       ... done
Pulling letsencrypt-nginx-proxy-companion ... done
Pulling netdata                           ... done
Pulling plex                              ... done
Pulling tautulli                          ... done
Creating network "docker_default" with the default driver
Creating nginx-proxy ... done
Creating plex        ... done
Creating letsencrypt ... done
Creating netdata     ... done
Creating tautulli    ... done

Cleaning Docker leftovers

Total reclaimed space: 0B

Patching server

Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic-security InRelease
Hit:5 https://download.docker.com/linux/ubuntu bionic InRelease
Hit:6 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Sun Dec  1 23:15:25 UTC 2019 - Done! Your system should be back online

Restoring permissions... this could take a few minutes
```

This time, the containers are started, I can get to Plex once again on port 32400, and my media is visible :) I'm a bit concerned about the `ERROR: The Compose file './docker-compose.yaml' is invalid` error though in the last output. Any thoughts?

**Comment by bifa2** [comment] 2019-12-01 23:22
I should have included *playing* media in my checking. I'm getting the message `Please check that the file exists and the necessary drive is mounted.` which is what I woke up to this morning. It seems as though rclone isn't mounted at the moment.

**Comment by TechPerplexed** [comment] 2019-12-01 23:51
First, glad Gooby is back in working order - to the point of not spitting out errors halfway rclean.

The mountpoint errors are actually the way it's supposed to work, so, on to the next stage of troubleshooting.

When you type 
ls /mnt/rclone
and
ls /mnt/google

Do you see your Google content?

**Comment by bifa2** [comment] 2019-12-02 00:02
`ls /mnt/rclone` hangs for a while then gives:
`ls: reading directory '/mnt/rclone': Input/output error`

`ls /mnt/google` shows a folder called `Downloads` which is not in my Google Drive.

**Comment by TechPerplexed** [comment] 2019-12-02 00:12
Can you see your content (folders) when you type 

`rclone lsd Gdrive:`
(or whatever you named your mount)?

If so, run these commands:

```
sudo systemctl daemon-reload
sudo systemctl stop mergerfs
sudo systemctl stop rclonefs
/bin/fusermount -uz /mnt/rclone
/bin/fusermount -uz /mnt/google
sudo chown -R $USER:$USER /mnt
sudo systemctl start rclonefs

```
Check if your content is in /mnt/rclone

If not, please report back. If yes, 

`sudo systemctl start rclonefs`

Then check if your content is also available at /mnt/google

**Comment by bifa2** [comment] 2019-12-02 00:20
Oooh, this is interesting. `rclone lsd GDrive-Movies:` gives "ERROR : : error listing: couldn't list directory: Get https..." ... long url and crucially:
```
Response: {
  "error": "unauthorized_client",
  "error_description": "Unauthorized"
}
```
Followed by ` Failed to lsd with 2 errors: last error was: couldn't list directory`, another long API url and then the same JSON response.

I have my own client_id and secret that I had presumed to be running fine until today. If I run `rclone config` and then choose to edit my remotes, it shows the existing remote config and my ID and secret are correct. Should I try refreshing the access token?

**Comment by TechPerplexed** [comment] 2019-12-02 00:26
Yeah, Rclone definitely isn't configured right.... I would just uninstall it and reinstall from scratch (or ask the Rclone forums for help. haha, I'm not that familiar with the ins and outs there)

**Comment by bifa2** [comment] 2019-12-02 00:31
I can possibly use the defaults, if need be (that is, leaving it blank). Meanwhile the output of:

```
sudo systemctl daemon-reload
sudo systemctl stop mergerfs
sudo systemctl stop rclonefs
/bin/fusermount -uz /mnt/rclone
/bin/fusermount -uz /mnt/google
sudo chown -R $USER:$USER /mnt
sudo systemctl start rclonefs`

is:

```
/bin/fusermount: entry for /mnt/rclone not found in /etc/mtab
/bin/fusermount: entry for /mnt/google not found in /etc/mtab
```

which probably isn't going to help. `/mnt/google` has vanished also.

**Comment by bifa2** [comment] 2019-12-02 00:37
Getting closer. Uninstall and reinstall of rclone now has my files visible under /mnt/google, but Plex still says: `Please check that the file exists and the necessary drive is mounted.`. Do we need to restart that container?

Please could you tell me where it detects the old rclone config? After the reinstall it just picked up my old config.

**Comment by TechPerplexed** [comment] 2019-12-02 01:05
Rclone config dwells in your home folder, in ~/.config/rclone

**Comment by TechPerplexed** [comment] 2019-12-02 02:59
Closing this for now, since your issues seem resolved and we basically hijacked @mr-handerson's thread to get there ;)

**Closed by TechPerplexed** 2019-12-02 02:59 UTC
