### ISSUE TITLE
Docker not installed?

### ISSUE THREAD

**Issue by thunderstorm654** [TechPerplexed/Gooby#117] opened 2020-02-11 17:27 UTC
Hi! I am trying to move to a new server. 
After installing Gooby I configured rclone then tried to restore a backup from my old server.
It did everything but then gave an error about Docker. I exited and then tried running docker and it seems it is not installed.
I have tried manually installing apps like Plex and Emby via the Gooby menus and there's a brief flash of an error about Docker but then the screen shows the usual success message - of course there isn't a success as docker isn't there so there's no containers :)

Any ideas how to fix a missing docker install?! Or should I just wipe the server and try again? It's Debian 10.2.

**Comment by TechPerplexed** [comment] 2020-02-11 17:51
Oof no idea off the bat, so you're saying that Docker installed correctly at first (since you installed Gooby successfully, right?) but after restoring your backup you get an error with Docker? What happens when you type `which docker`?

**Comment by thunderstorm654** [comment] 2020-02-11 17:59
Well to be honest I don't know it was ever actually working... The install appeared to go okay but docker doesn't exist at all, just doesn't recognise the command. I noticed then that there was an error in the packages list, when I try to update the packages manually it has a 404 with the docker URL.
I'm going to reset the server and give it another go with the same version of Debian I had previously. Thanks for the swift reply btw! :)

**Comment by thunderstorm654** [comment] 2020-02-11 18:15
I managed to screenshot the install this time..
![Screenshot_20200211-181306](https://user-images.githubusercontent.com/16837607/74265325-47e5d100-4cfa-11ea-80b0-c937c9fc2f9a.png)

Yes I am doing this on mobile this time sorry it's tiny! Have you seen this before? There seems to be no release file in the Docker repo :/. Appreciate this is unlikely to be your issue, but the Gooby installer I guess won't work in the meantime.

**Comment by thunderstorm654** [comment] 2020-02-11 19:17
Ok so I tried using Ubuntu instead and now it's installed :) weird! Would it be a bad idea to restore a Gooby backup from the old working Debian server?

**Comment by TechPerplexed** [comment] 2020-02-11 19:28
Oh pfew, so it's probably something to keep an eye on with future Debian updates - thanks for the heads up!
It doesn't matter one bit if you restore a formerly Debian Gooby to Ubuntu, that is the beauty of Docker :)

I'll probably be testing Gooby on 10.2 soon, see if I can reproduce your errors. Let me know if you have more questions, meanwhile I'll close this issue since it seems to be resolved for now :)

**Closed by TechPerplexed** 2020-02-11 19:28 UTC

**Comment by doob187** [comment] 2020-03-01 14:39
https://github.com/TechPerplexed/Gooby/pull/118/commits/73c25c36d64f8047b7ae566a65377f65107178b3
